---
- name: Install Ldap (389-ds)
  hosts: all
  become: true

  tasks:
  - name: Update
    apt: update_cache=yes

  - name: Install Ldap
    apt: name=389-ds state=latest

  - name: Install Ldap - base
    apt: name=389-ds-base state=latest