- name: Installing - FTP - ApacheServer - VNC
  hosts: localhost
  connection: local
  become: 'True'
  vars:
    vm_id: Kali-Linux-2020_1674
    app_user: root
    http_host: ApacheTest
    http_conf: ApacheTest.conf
    http_port: '80'
  tasks:
  - name: Update APT update
    vmware_vm_shell:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      vm_shell: /usr/bin/apt-get
      vm_shell_args: update
  - name: Install the vsftpd
    vmware_vm_shell:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      vm_shell: /usr/bin/apt
      vm_shell_args: install -y vsftpd
  - name: Start vsftpd
    vmware_vm_shell:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      vm_shell: /usr/sbin/service
      vm_shell_args: vsftpd start
  - name: Enable vsftpd
    vmware_vm_shell:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      vm_shell: /usr/sbin/service
      vm_shell_args: vsftpd enable
  - name: Copy /etc/vsftpd.conf
    vmware_vm_shell:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      vm_shell: /usr/bin/cp
      vm_shell_args: /etc/vsftpd.conf /etc/vsftpd.conf_default
  - name: Install UFW
    vmware_vm_shell:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      vm_shell: /usr/bin/apt
      vm_shell_args: install ufw
  - name: Enable ufw
    vmware_vm_shell:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      vm_shell: /usr/sbin/ufw
      vm_shell_args: enable
  - name: UFW - Allow 20/tcp
    vmware_vm_shell:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      vm_shell: /usr/sbin/ufw
      vm_shell_args: allow 20/tcp
  - name: UFW - Allow 21/tcp
    vmware_vm_shell:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      vm_shell: /usr/sbin/ufw
      vm_shell_args: allow 21/tcp
  - name: Install Aptitude
    vmware_vm_shell:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      vm_shell: /usr/bin/apt
      vm_shell_args: install -y aptitude
  - name: Install Apache2
    vmware_vm_shell:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      vm_shell: /usr/bin/apt
      vm_shell_args: install -y apache2
  - name: Create document root
    vmware_vm_shell:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      vm_shell: /usr/bin/mkdir
      vm_shell_args: -m 0755 /var/www/{{ http_host }}
  - name: Copy index test page
    vmware_guest_file_operation:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      copy:
        src: ApacheServer/apacheIndex.html.j2
        dest: /var/www/{{ http_host }}/index.html
        overwrite: true
  - name: Set up Apache virtualhost
    vmware_guest_file_operation:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      copy:
        src: ApacheServer/apacheConf.conf.j2
        dest: /etc/apache2/sites-available/{{ http_conf }}
        overwrite: true
  - name: Disable default Apache site
    vmware_vm_shell:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      vm_shell: /usr/sbin/a2dissite
      vm_shell_args: 000-default.conf
  - name: Enable new site
    vmware_vm_shell:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      vm_shell: /usr/sbin/a2ensite
      vm_shell_args: ApacheTest.conf
    notify: Reload Apache
  - name: Install UFW
    vmware_vm_shell:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      vm_shell: /usr/bin/apt
      vm_shell_args: install ufw
  - name: Enable ufw
    vmware_vm_shell:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      vm_shell: /usr/sbin/ufw
      vm_shell_args: enable
  - name: UFW - Allow HTTP on port {{ http_port }}
    vmware_vm_shell:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      vm_shell: /usr/sbin/ufw
      vm_shell_args: allow {{ http_port }}
    notify: Reload Apache
  - name: Install tightvncserver
    vmware_vm_shell:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      vm_shell: /usr/bin/apt
      vm_shell_args: install -y tightvncserver
  - name: Install the GUI and VNC Packages
    vmware_vm_shell:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      vm_shell: /usr/bin/apt
      vm_shell_args: install -y gnome-core
  - name: Install the GUI and VNC Packages 2
    vmware_vm_shell:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      vm_shell: /usr/bin/apt
      vm_shell_args: install -y vnc4server
  - name: Copy the defult password file
    vmware_guest_file_operation:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      copy:
        src: VNC/password
        dest: /tmp/file
        overwrite: true
  - name: bash vncserver command
    vmware_vm_shell:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      vm_shell_cwd: /usr/local
      vm_shell: /usr/bin/bash
      vm_shell_args: sudo -u student -i vncserver </tmp/file >/tmp/vncpasswd.1 2>/tmp/vncpasswd.2
  - name: Copy the vncservers.conf file in /etc/ directory
    vmware_guest_file_operation:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      copy:
        src: VNC/vncservers.conf.j2
        dest: /etc/vncservers.conf
        overwrite: true
  - name: Copy the modified "xstartup" file
    vmware_guest_file_operation:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      copy:
        src: VNC/xstartup.j2
        dest: /root/.vnc/xstartup
        overwrite: true
  - name: Create a file vncserver in /etc/init.d/directory
    vmware_guest_file_operation:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      copy:
        src: VNC/vncserver.j2
        dest: /etc/init.d/vncserver
        overwrite: true
  - name: Add vncserver service to default runlevels
    vmware_vm_shell:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      vm_shell_cwd: /usr/local
      vm_shell: /usr/sbin/update-rc.d
      vm_shell_args: vncserver defaults
  - name: Restart VNC Service
    vmware_vm_shell:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      vm_shell: /usr/bin/systemctl
      vm_shell_args: list-units /etc/init.d/vncserver restart vncserver
  handlers:
  - name: Reload Apache
    vmware_vm_shell:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      vm_shell: /usr/bin/systemctl
      vm_shell_args: start apache2
  - name: Restart Apache
    vmware_vm_shell:
      hostname: '{{ vcenter_ip }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter: '{{ datacenter }}'
      validate_certs: false
      vm_id: '{{ vm_id }}'
      vm_username: root
      vm_password: kali
      vm_shell: /usr/bin/systemctl
      vm_shell_args: restart apache2
