- name: Install Apache Tomcat
  hosts: localhost
  connection: local
  become: True

  vars:
    vm_id: "Kali-Linux-2020_1644"

  tasks:
  - name: Install OpenJDK
    vmware_vm_shell:
     hostname: "{{ vcenter_ip }}"
     username: "{{ vcenter_username }}"
     password: "{{ vcenter_password }}"
     datacenter: "{{ datacenter }}"
     validate_certs: no
     vm_id: "{{ vm_id }}"
     vm_username: root
     vm_password: kali
     vm_shell: "/usr/bin/apt"
     vm_shell_args: "install openjdk-11-jre-headless"

  - name: download tomcat server packages
    vmware_vm_shell:
     hostname: "{{ vcenter_ip }}"
     username: "{{ vcenter_username }}"
     password: "{{ vcenter_password }}"
     datacenter: "{{ datacenter }}"
     validate_certs: no
     vm_id: "{{ vm_id }}"
     vm_username: root
     vm_password: kali
     vm_shell_cwd: "/usr/local"
     vm_shell: "/usr/bin/wget"
     vm_shell_args: "https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.79/bin/apache-tomcat-8.5.79.tar.gz"

  - name: extract tomcat packages
    vmware_vm_shell:
     hostname: "{{ vcenter_ip }}"
     username: "{{ vcenter_username }}"
     password: "{{ vcenter_password }}"
     datacenter: "{{ datacenter }}"
     validate_certs: no
     vm_id: "{{ vm_id }}"
     vm_username: root
     vm_password: kali
     vm_shell_cwd: "/usr/local"
     vm_shell: "/usr/bin/tar"
     vm_shell_args: "xvzf apache-tomcat-8.5.79.tar.gz"

  - name: start tomcat services
    vmware_vm_shell:
     hostname: "{{ vcenter_ip }}"
     username: "{{ vcenter_username }}"
     password: "{{ vcenter_password }}"
     datacenter: "{{ datacenter }}"
     validate_certs: no
     vm_id: "{{ vm_id }}"
     vm_username: root
     vm_password: kali
     vm_shell_cwd: "/usr/local"
     vm_shell: "/usr/bin/nohup"
     vm_shell_args: "/usr/local/apache-tomcat-8.5.79/bin/startup.sh"