- name: Installing Citrix
  hosts: localhost
  connection: local
  become: True

  vars:
    vm_id: "Kali-Linux-2020_1644"
    
  tasks:
    - name: Install Citrix Workspace
      vmware_vm_shell:
       hostname: "{{ vcenter_ip }}"
       username: "{{ vcenter_username }}"
       password: "{{ vcenter_password }}"
       datacenter: "{{ datacenter }}"
       validate_certs: no
       vm_id: "{{ vm_id }}"
       vm_username: root
       vm_password: kali
       vm_shell_cwd: "/usr/local"
       vm_shell: "/usr/bin/wget"
       vm_shell_args: "https://downloads.citrix.com/20380/icaclient_22.2.0.20_amd64.deb?__gda__=exp=1645650897~acl=/*~hmac=53253584d67a383df3fd0cd2de13165bc700d8801843f7819f552b3fd8078c97"

    - name: Install libicu60 60.2-3ubuntu3
      vmware_vm_shell:
       hostname: "{{ vcenter_ip }}"
       username: "{{ vcenter_username }}"
       password: "{{ vcenter_password }}"
       datacenter: "{{ datacenter }}"
       validate_certs: no
       vm_id: "{{ vm_id }}"
       vm_username: root
       vm_password: kali
       vm_shell_cwd: "/usr/local"
       vm_shell: "/usr/bin/wget"
       vm_shell_args: "http://launchpadlibrarian.net/361669149/libicu60_60.2-3ubuntu3_amd64.deb"

    - name: Install libjavascriptcoregtk-1.0-0 2.4.11-3ubuntu3
      vmware_vm_shell:
       hostname: "{{ vcenter_ip }}"
       username: "{{ vcenter_username }}"
       password: "{{ vcenter_password }}"
       datacenter: "{{ datacenter }}"
       validate_certs: no
       vm_id: "{{ vm_id }}"
       vm_username: root
       vm_password: kali
       vm_shell_cwd: "/usr/local"
       vm_shell: "/usr/bin/wget"
       vm_shell_args: "http://launchpadlibrarian.net/344880889/libjavascriptcoregtk-1.0-0_2.4.11-3ubuntu3_amd64.deb"

    - name: Install libwebkitgtk-1.0-0 2.4.11-3ubuntu3
      vmware_vm_shell:
       hostname: "{{ vcenter_ip }}"
       username: "{{ vcenter_username }}"
       password: "{{ vcenter_password }}"
       datacenter: "{{ datacenter }}"
       validate_certs: no
       vm_id: "{{ vm_id }}"
       vm_username: root
       vm_password: kali
       vm_shell_cwd: "/usr/local"
       vm_shell: "/usr/bin/wget"
       vm_shell_args: "http://launchpadlibrarian.net/344880892/libwebkitgtk-1.0-0_2.4.11-3ubuntu3_amd64.deb"

    - name: Install libwebkit-1.0-2 1.2.0-1 
      vmware_vm_shell:
       hostname: "{{ vcenter_ip }}"
       username: "{{ vcenter_username }}"
       password: "{{ vcenter_password }}"
       datacenter: "{{ datacenter }}"
       validate_certs: no
       vm_id: "{{ vm_id }}"
       vm_username: root
       vm_password: kali
       vm_shell_cwd: "/usr/local"
       vm_shell: "/usr/bin/wget"
       vm_shell_args: "http://launchpadlibrarian.net/43503990/libwebkit-1.0-2_1.2.0-1_amd64.deb"

    - name: dpkg libicu60_60.2-3ubuntu3_amd64.deb
      vmware_vm_shell:
       hostname: "{{ vcenter_ip }}"
       username: "{{ vcenter_username }}"
       password: "{{ vcenter_password }}"
       datacenter: "{{ datacenter }}"
       validate_certs: no
       vm_id: "{{ vm_id }}"
       vm_username: root
       vm_password: kali
       vm_shell_cwd: "/usr/local"
       vm_shell: "/usr/bin/dpkg"
       vm_shell_args: "-i libicu60_60.2-3ubuntu3_amd64.deb"

    - name: dpkg libjavascriptcoregtk-1.0-0_2.4.11-3ubuntu3_amd64.deb
      vmware_vm_shell:
       hostname: "{{ vcenter_ip }}"
       username: "{{ vcenter_username }}"
       password: "{{ vcenter_password }}"
       datacenter: "{{ datacenter }}"
       validate_certs: no
       vm_id: "{{ vm_id }}"
       vm_username: root
       vm_password: kali
       vm_shell_cwd: "/usr/local"
       vm_shell: "/usr/bin/dpkg"
       vm_shell_args: "-i libjavascriptcoregtk-1.0-0_2.4.11-3ubuntu3_amd64.deb"

    - name: dpkg libwebkit-1.0-2_1.2.0-1_amd64.deb
      vmware_vm_shell:
       hostname: "{{ vcenter_ip }}"
       username: "{{ vcenter_username }}"
       password: "{{ vcenter_password }}"
       datacenter: "{{ datacenter }}"
       validate_certs: no
       vm_id: "{{ vm_id }}"
       vm_username: root
       vm_password: kali
       vm_shell_cwd: "/usr/local"
       vm_shell: "/usr/bin/dpkg"
       vm_shell_args: "-i libwebkit-1.0-2_1.2.0-1_amd64.deb"

    - name: dpkg libwebkitgtk-1.0-0_2.4.11-3ubuntu3_amd64.deb
      vmware_vm_shell:
       hostname: "{{ vcenter_ip }}"
       username: "{{ vcenter_username }}"
       password: "{{ vcenter_password }}"
       datacenter: "{{ datacenter }}"
       validate_certs: no
       vm_id: "{{ vm_id }}"
       vm_username: root
       vm_password: kali
       vm_shell_cwd: "/usr/local"
       vm_shell: "/usr/bin/dpkg"
       vm_shell_args: "-i libwebkitgtk-1.0-0_2.4.11-3ubuntu3_amd64.deb"
     
    - name: dpkg icaclient_22.2.0.20_amd64.deb
      vmware_vm_shell:
       hostname: "{{ vcenter_ip }}"
       username: "{{ vcenter_username }}"
       password: "{{ vcenter_password }}"
       datacenter: "{{ datacenter }}"
       validate_certs: no
       vm_id: "{{ vm_id }}"
       vm_username: root
       vm_password: kali
       vm_shell_cwd: "/usr/local"
       vm_shell: "/usr/bin/dpkg"
       vm_shell_args: "-i icaclient_22.2.0.20_amd64.deb"