- name: Installing MongoDB
  hosts: localhost
  connection: local
  become: True

  vars:
    vm_id: "Kali-Linux-2020_1644"

  tasks:
  - name: Install mongodb
    vmware_vm_shell:
     hostname: "{{ vcenter_ip }}"
     username: "{{ vcenter_username }}"
     password: "{{ vcenter_password }}"
     datacenter: "{{ datacenter }}"
     validate_certs: no
     vm_id: "{{ vm_id }}"
     vm_username: root
     vm_password: kali
     vm_shell: "/usr/bin/apt"
     vm_shell_args: "install mongodb"

  - name: Copy config file
    vmware_guest_file_operation:
     hostname: "{{ vcenter_ip }}"
     username: "{{ vcenter_username }}"
     password: "{{ vcenter_password }}"
     datacenter: "{{ datacenter }}"
     validate_certs: no
     vm_id: "{{ vm_id }}"
     vm_username: root
     vm_password: kali
     copy:
         src: "MongoDB/mongodb.conf"
         dest: "/etc/mongodb.conf"
         overwrite: True

  - name: Restart MongoDB
    vmware_vm_shell:
     hostname: "{{ vcenter_ip }}"
     username: "{{ vcenter_username }}"
     password: "{{ vcenter_password }}"
     datacenter: "{{ datacenter }}"
     validate_certs: no
     vm_id: "{{ vm_id }}"
     vm_username: root
     vm_password: kali
     vm_shell: "/usr/sbin/service"
     vm_shell_args: "mongodb restart"

  - name: Create /etc/security/limits.d/mongodb.conf
    vmware_guest_file_operation:
     hostname: "{{ vcenter_ip }}"
     username: "{{ vcenter_username }}"
     password: "{{ vcenter_password }}"
     datacenter: "{{ datacenter }}"
     validate_certs: no
     vm_id: "{{ vm_id }}"
     vm_username: root
     vm_password: kali
     copy:
         src: "MongoDB/security-mongodb.conf"
         dest: "/etc/security/limits.d/mongodb.conf"
         overwrite: True
  
  - name: Restart MongoDB
    vmware_vm_shell:
     hostname: "{{ vcenter_ip }}"
     username: "{{ vcenter_username }}"
     password: "{{ vcenter_password }}"
     datacenter: "{{ datacenter }}"
     validate_certs: no
     vm_id: "{{ vm_id }}"
     vm_username: root
     vm_password: kali
     vm_shell: "/usr/sbin/service"
     vm_shell_args: "mongodb restart"

  - name: Set vm.dirty_ratio
    vmware_vm_shell:
     hostname: "{{ vcenter_ip }}"
     username: "{{ vcenter_username }}"
     password: "{{ vcenter_password }}"
     datacenter: "{{ datacenter }}"
     validate_certs: no
     vm_id: "{{ vm_id }}"
     vm_username: root
     vm_password: kali
     vm_shell: "/usr/sbin/sysctl"
     vm_shell_args: "-w vm.dirty_ratio=15"  

  - name: Set vm.dirty_background_ratio
    vmware_vm_shell:
     hostname: "{{ vcenter_ip }}"
     username: "{{ vcenter_username }}"
     password: "{{ vcenter_password }}"
     datacenter: "{{ datacenter }}"
     validate_certs: no
     vm_id: "{{ vm_id }}"
     vm_username: root
     vm_password: kali
     vm_shell: "/usr/sbin/sysctl"
     vm_shell_args: "-w vm.dirty_background_ratio=5"

  - name: Set vm.swappiness
    vmware_vm_shell:
     hostname: "{{ vcenter_ip }}"
     username: "{{ vcenter_username }}"
     password: "{{ vcenter_password }}"
     datacenter: "{{ datacenter }}"
     validate_certs: no
     vm_id: "{{ vm_id }}"
     vm_username: root
     vm_password: kali
     vm_shell: "/usr/sbin/sysctl"
     vm_shell_args: "-w vm.swappiness=10"

  - name: Set net.core.somaxconn
    vmware_vm_shell:
     hostname: "{{ vcenter_ip }}"
     username: "{{ vcenter_username }}"
     password: "{{ vcenter_password }}"
     datacenter: "{{ datacenter }}"
     validate_certs: no
     vm_id: "{{ vm_id }}"
     vm_username: root
     vm_password: kali
     vm_shell: "/usr/sbin/sysctl"
     vm_shell_args: "-w net.core.somaxconn=4096"

  - name: Set net.ipv4.tcp_fin_timeout
    vmware_vm_shell:
     hostname: "{{ vcenter_ip }}"
     username: "{{ vcenter_username }}"
     password: "{{ vcenter_password }}"
     datacenter: "{{ datacenter }}"
     validate_certs: no
     vm_id: "{{ vm_id }}"
     vm_username: root
     vm_password: kali
     vm_shell: "/usr/sbin/sysctl"
     vm_shell_args: "-w net.ipv4.tcp_fin_timeout=30"

  - name: Set net.ipv4.tcp_keepalive_intvl
    vmware_vm_shell:
     hostname: "{{ vcenter_ip }}"
     username: "{{ vcenter_username }}"
     password: "{{ vcenter_password }}"
     datacenter: "{{ datacenter }}"
     validate_certs: no
     vm_id: "{{ vm_id }}"
     vm_username: root
     vm_password: kali
     vm_shell: "/usr/sbin/sysctl"
     vm_shell_args: "-w net.ipv4.tcp_keepalive_intvl=30"

  - name: Set net.ipv4.tcp_keepalive_time
    vmware_vm_shell:
     hostname: "{{ vcenter_ip }}"
     username: "{{ vcenter_username }}"
     password: "{{ vcenter_password }}"
     datacenter: "{{ datacenter }}"
     validate_certs: no
     vm_id: "{{ vm_id }}"
     vm_username: root
     vm_password: kali
     vm_shell: "/usr/sbin/sysctl"
     vm_shell_args: "-w net.ipv4.tcp_keepalive_time=120"

  - name: Set net.ipv4.tcp_max_syn_backlog
    vmware_vm_shell:
     hostname: "{{ vcenter_ip }}"
     username: "{{ vcenter_username }}"
     password: "{{ vcenter_password }}"
     datacenter: "{{ datacenter }}"
     validate_certs: no
     vm_id: "{{ vm_id }}"
     vm_username: root
     vm_password: kali
     vm_shell: "/usr/sbin/sysctl"
     vm_shell_args: "-w net.ipv4.tcp_max_syn_backlog=4096"

  - name: Install ntp
    vmware_vm_shell:
     hostname: "{{ vcenter_ip }}"
     username: "{{ vcenter_username }}"
     password: "{{ vcenter_password }}"
     datacenter: "{{ datacenter }}"
     validate_certs: no
     vm_id: "{{ vm_id }}"
     vm_username: root
     vm_password: kali
     vm_shell: "/usr/bin/apt"
     vm_shell_args: "install -y ntp"

  - name: Start mongodb
    vmware_vm_shell:
     hostname: "{{ vcenter_ip }}"
     username: "{{ vcenter_username }}"
     password: "{{ vcenter_password }}"
     datacenter: "{{ datacenter }}"
     validate_certs: no
     vm_id: "{{ vm_id }}"
     vm_username: root
     vm_password: kali
     vm_shell: "/usr/sbin/service"
     vm_shell_args: "mongodb start"

  - name: Enable mongodb
    vmware_vm_shell:
     hostname: "{{ vcenter_ip }}"
     username: "{{ vcenter_username }}"
     password: "{{ vcenter_password }}"
     datacenter: "{{ datacenter }}"
     validate_certs: no
     vm_id: "{{ vm_id }}"
     vm_username: root
     vm_password: kali
     vm_shell: "/usr/sbin/service"
     vm_shell_args: "mongodb enable"