- name: Installing Kerberos
  hosts: localhost
  connection: local
  become: True

  vars:
    vm_id: "Kali-Linux-2020_1644"
    sshd_port: "22"
    sshd_listen_address: ["::", "0.0.0.0"]
    sshd_allow_groups: []
    sshd_protocol: "2"
    sshd_host_keys: ["ed25519", "rsa", "ecdsa"]
    sshd_kex_algorithms:
      - "curve25519-sha256@libssh.org"
      - "ecdh-sha2-nistp521"
      - "ecdh-sha2-nistp384"
      - "ecdh-sha2-nistp256"
      - "diffie-hellman-group-exchange-sha256"
    sshd_ciphers:
      - "chacha20-poly1305@openssh.com"
      - "aes256-gcm@openssh.com"
      - "aes128-gcm@openssh.com"
      - "aes256-ctr"
      - "aes192-ctr"
      - "aes128-ctr"
    sshd_macs:
      - "hmac-sha2-512-etm@openssh.com"
      - "hmac-sha2-256-etm@openssh.com"
      - "umac-128-etm@openssh.com"
      - "hmac-sha2-512"
      - "hmac-sha2-256"
      - "umac-128@openssh.com"
    sshd_use_privilege_separation: "yes"
    sshd_key_regeneration_interval: "3600"
    sshd_server_key_bits: "1024"
    sshd_syslog_facility: "AUTH"
    sshd_log_level: "INFO"
    sshd_login_grace_time: "120"
    sshd_permit_root_login: "no"
    sshd_strict_modes: "yes"
    sshd_rsa_authentication: "yes"
    sshd_pubkey_authentication: "yes"
    sshd_authorized_keys_file: "%h/.ssh/authorized_keys"
    sshd_ignore_rhosts: "yes"
    sshd_rhosts_rsa_authentication: "no"
    sshd_host_based_authentication: "no"
    sshd_ignore_user_known_hosts: "no"
    sshd_permit_empty_passwords: "no"
    sshd_challenge_response_authentication: "no"
    sshd_password_authentication: "no"
    sshd_gss_api_authentication: "no"
    sshd_gss_api_cleanup_credentials: "yes"
    sshd_x11_forwarding: "yes"
    sshd_x11_display_offset: "10"
    sshd_print_motd: "no"
    sshd_print_last_log: "yes"
    sshd_tcp_keep_alive: "yes"
    sshd_max_startups: "10:30:100"
    sshd_banner: "none"
    sshd_accept_env: "LANG LC_*"
    sshd_subsystem: "sftp /usr/lib/openssh/sftp-server"
    sshd_use_pam: "yes"
    
  tasks:
    - name: Update APT update
      vmware_vm_shell:
       hostname: "{{ vcenter_ip }}"
       username: "{{ vcenter_username }}"
       password: "{{ vcenter_password }}"
       datacenter: "{{ datacenter }}"
       validate_certs: no
       vm_id: "{{ vm_id }}"
       vm_username: root
       vm_password: kali
       vm_shell: "/usr/bin/apt-get"
       vm_shell_args: "update"

    - name: Install OpenSSH server
      vmware_vm_shell:
       hostname: "{{ vcenter_ip }}"
       username: "{{ vcenter_username }}"
       password: "{{ vcenter_password }}"
       datacenter: "{{ datacenter }}"
       validate_certs: no
       vm_id: "{{ vm_id }}"
       vm_username: root
       vm_password: kali
       vm_shell: "/usr/bin/apt"
       vm_shell_args: "install -y openssh-server"
      notify: ["Test and restart SSHD"]

    - name: Ensure Ed25519 host key is present
      vmware_vm_shell:
       hostname: "{{ vcenter_ip }}"
       username: "{{ vcenter_username }}"
       password: "{{ vcenter_password }}"
       datacenter: "{{ datacenter }}"
       validate_certs: no
       vm_id: "{{ vm_id }}"
       vm_username: root
       vm_password: kali
       vm_shell_cwd: "/etc/ssh"
       vm_shell: "/usr/bin/ssh-keygen"
       vm_shell_args: '-q -t ed25519 -N "" -f ssh_host_ed25519_key'

    - name: Generate SSHD config
      vmware_guest_file_operation:
       hostname: "{{ vcenter_ip }}"
       username: "{{ vcenter_username }}"
       password: "{{ vcenter_password }}"
       datacenter: "{{ datacenter }}"
       validate_certs: no
       vm_id: "{{ vm_id }}"
       vm_username: root
       vm_password: kali
       copy:
           src: "Openssh/sshd_config.j2"
           dest: "/etc/ssh/sshd_config"
           overwrite: True
      notify: Test and restart SSHD
  
  handlers:
    - name: Test and restart SSHD
      vmware_vm_shell:
       hostname: "{{ vcenter_ip }}"
       username: "{{ vcenter_username }}"
       password: "{{ vcenter_password }}"
       datacenter: "{{ datacenter }}"
       validate_certs: no
       vm_id: "{{ vm_id }}"
       vm_username: root
       vm_password: kali
       vm_shell: "/usr/bin/bash"
       vm_shell_args: "sshd -t"
      notify: Restart SSHD

    - name: Restart SSHD
      vmware_vm_shell:
       hostname: "{{ vcenter_ip }}"
       username: "{{ vcenter_username }}"
       password: "{{ vcenter_password }}"
       datacenter: "{{ datacenter }}"
       validate_certs: no
       vm_id: "{{ vm_id }}"
       vm_username: root
       vm_password: kali
       vm_shell: "/usr/sbin/service"
       vm_shell_args: "ssh restart"