- name: Installing Redis
  hosts: localhost
  connection: local
  become: True

  vars:
    vm_id: "Kali-Linux-2020_1644"

  tasks:
  - name: Update APT package manager repositories cache
    vmware_vm_shell:
     hostname: "{{ vcenter_ip }}"
     username: "{{ vcenter_username }}"
     password: "{{ vcenter_password }}"
     datacenter: "{{ datacenter }}"
     validate_certs: no
     vm_id: "{{ vm_id }}"
     vm_username: root
     vm_password: kali
     vm_shell: "/usr/bin/apt"
     vm_shell_args: "update"

  - name: Install redis-server
    vmware_vm_shell:
     hostname: "{{ vcenter_ip }}"
     username: "{{ vcenter_username }}"
     password: "{{ vcenter_password }}"
     datacenter: "{{ datacenter }}"
     validate_certs: no
     vm_id: "{{ vm_id }}"
     vm_username: root
     vm_password: kali
     vm_shell: "/usr/bin/apt"
     vm_shell_args: "install redis-server"

  - name: Restart Redis Server
    vmware_vm_shell:
     hostname: "{{ vcenter_ip }}"
     username: "{{ vcenter_username }}"
     password: "{{ vcenter_password }}"
     datacenter: "{{ datacenter }}"
     validate_certs: no
     vm_id: "{{ vm_id }}"
     vm_username: root
     vm_password: kali
     vm_shell: "/usr/sbin/service"
     vm_shell_args: "redis restart"
  