---
- name: install apache-struts
  hosts: all
  become: true

  tasks:
  - name: Install OpenJDK
    apt:
      name: openjdk-11-jre-headless

  - name: download struts packages
    get_url:
      url: https://dlcdn.apache.org/struts/2.5.29/struts-2.5.29-all.zip
      dest: /usr/local/

  - name: install zip/unzip
    script: comm.sh

  - name: extract struts packages
    ansible.builtin.unarchive:
      src: /usr/local/struts-2.5.29-all.zip
      dest: /usr/local/
      remote_src: yes