---
- name: Install Citrix
  hosts: all
  become: true

  tasks:
  - name: Install Citrix Workspace
    get_url:
      url: https://downloads.citrix.com/20380/icaclient_22.2.0.20_amd64.deb?__gda__=exp=1645650897~acl=/*~hmac=53253584d67a383df3fd0cd2de13165bc700d8801843f7819f552b3fd8078c97
      dest: /usr/local

  - name: Install libicu60 60.2-3ubuntu3
    get_url:
      url: http://launchpadlibrarian.net/361669149/libicu60_60.2-3ubuntu3_amd64.deb
      dest: /usr/local

  - name: Install libjavascriptcoregtk-1.0-0 2.4.11-3ubuntu3
    get_url:
      url: http://launchpadlibrarian.net/344880889/libjavascriptcoregtk-1.0-0_2.4.11-3ubuntu3_amd64.deb
      dest: /usr/local

  - name: Install libwebkitgtk-1.0-0 2.4.11-3ubuntu3
    get_url:
      url: http://launchpadlibrarian.net/344880892/libwebkitgtk-1.0-0_2.4.11-3ubuntu3_amd64.deb
      dest: /usr/local
  
  - name: Install libwebkit-1.0-2 1.2.0-1 
    get_url:
      url: http://launchpadlibrarian.net/43503990/libwebkit-1.0-2_1.2.0-1_amd64.deb
      dest: /usr/local

  - name: Apply script 
    script: comm.sh
    ignore_errors: true
     
  - name: Apply script for citrix
    script: commCitrix.sh   
    ignore_errors: true