- hosts: all
  become: yes
  tasks:

    - name: Update
      apt: update_cache=yes   
   
    - name: Installing Redis
      apt: name=redis-server state=latest

    - name: Restart Redis Server
      service: name=redis state=restarted enabled=yes