---
- name: install apache-struts
  hosts: all
  become: true

  tasks:
  - name: Link /dev/random to /dev/urandom
    file:
      path: /dev/random
      src: /dev/urandom
      state: link
      force: yes
  
  - name: Install via apt KDC Server 1
    apt: "name=krb5-kdc state=present" 
  
  - name: Install via yum KDC Server 2
    apt: "name=krb5-admin-server state=present"

  - name: Makekrb5 newrealm
    shell: "krb5_newrealm"
    args: 
      stdin: "\n"